services:
  web:
    build: .
    container_name: edvardkuryla-web
    volumes:
      - .:/app   # монтируем проект внутрь контейнера
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # Любые переменные окружения для FastAPI
      - DATABASE_URL=postgresql://admin:1234@db:5432/database

  db:
    image: postgres:15
    container_name: edvardkuryla-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: database
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
